config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gameboards
  root 'gameboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gameboard.rb
class Gameboard < ApplicationRecord
  has_one_attached :board_box
  has_one_attached :board_rule
  has_many_attached :pieces
  has_many_attached :board_parts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gameboards_controller.rb
class GameboardsController < ApplicationController
  before_action :set_gameboard, only: [:show, :edit, :update, :destroy]

  # GET /gameboards
  # GET /gameboards.json
  def index
    @gameboards = Gameboard.all
  end

  # GET /gameboards/1
  # GET /gameboards/1.json
  def show
  end

  # GET /gameboards/new
  def new
    @gameboard = Gameboard.new
  end

  # GET /gameboards/1/edit
  def edit
  end

  # POST /gameboards
  # POST /gameboards.json
  def create
    @gameboard = Gameboard.new(gameboard_params)

    respond_to do |format|
      if @gameboard.save
        format.html { redirect_to @gameboard, notice: 'Gameboard was successfully created.' }
        format.json { render :show, status: :created, location: @gameboard }
      else
        format.html { render :new }
        format.json { render json: @gameboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gameboards/1
  # PATCH/PUT /gameboards/1.json
  def update
    respond_to do |format|
      if @gameboard.update(gameboard_params)
        format.html { redirect_to @gameboard, notice: 'Gameboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @gameboard }
      else
        format.html { render :edit }
        format.json { render json: @gameboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gameboards/1
  # DELETE /gameboards/1.json
  def destroy
    @gameboard.destroy
    respond_to do |format|
      format.html { redirect_to gameboards_url, notice: 'Gameboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gameboard
      @gameboard = Gameboard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gameboard_params
      params.require(:gameboard).permit(
        :name,
        :rules,
        :board_box,
        :board_rule,
        pieces: [],
        board_parts: []
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gameboards_helper.rb
module GameboardsHelper
end

app/views/gameboards/_form.html.erb
<%= form_with(model: gameboard, local: true) do |form| %>
  <% if gameboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gameboard.errors.count, "error") %> prohibited this gameboard from being saved:</h2>
      <ul>
        <% gameboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group py-2">
    <%= form.label :name, 'Nombre' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group py-2">
    <%= form.label :rules, 'Reglas' %>
    <%= form.text_area :rules, class: 'form-control' %>
  </div>
  <div class="form-group py-2">
    <%= form.label :board_box, 'Caja' %>
    <%= form.file_field :board_box, class: 'form-control-file' %>
  </div>
  <div class="form-group py-2">
    <%= form.label :board_rule, 'Manual de Reglas' %>
    <%= form.file_field :board_rule, class: 'form-control-file' %>
    <small id="emailHelp" class="form-text text-muted">Formato soportado: PDF</small>
  </div>
  <div class="form-group py-2">
    <%= form.label :pieces, 'Piezas de Tablero' %>
    <%= form.file_field :pieces, multiple: true, class: 'form-control-file' %>
  </div>
  <div class="form-group py-2">
    <%= form.label :board_parts, 'Partes del Tablero' %>
    <%= form.file_field :board_parts, multiple: true, class: 'form-control-file' %>
  </div>
  <div class="actions py-2">
    <%= form.submit 'Agregar Tablero', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/gameboards/edit.html.erb
<h1 class="py-4">Editar Tablero</h1>

<%= render 'form', gameboard: @gameboard %>

<div class="btn-group py-4" role="group" aria-label="Basic example">
  <%= link_to 'Ver', @gameboard, class: 'btn btn-secondary' %>
  <%= link_to 'Atrás', gameboards_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/gameboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="py-4">Tableros</h1>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Imagen</th>
      <th scope="col">Nombre</th>
      <th scope="col">Reglas</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @gameboards.each do |gameboard| %>
      <tr>
        <td><%= image_tag gameboard.board_box.variant(resize: "100x100", type: :grayscale).processed %></td>
        <td><%= gameboard.name %></td>
        <td><%= gameboard.rules %></td>
        <td><%= link_to 'Ver', gameboard %></td>
        <td><%= link_to 'Editar', edit_gameboard_path(gameboard) %></td>
        <td><%= link_to 'Eliminar', gameboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar Tablero', new_gameboard_path, class: 'btn btn-secondary' %>

app/views/gameboards/new.html.erb
<h1 class="py-4">Agregar Tablero</h1>

<%= render 'form', gameboard: @gameboard %>

<%= link_to 'Back', gameboards_path %>

app/views/gameboards/show.html.erb
<p id="notice"><%= notice %></p>
<div class="pt-4">
  <h1><%= @gameboard.name %></h1>
  <%= image_tag @gameboard.board_box.variant(resize: "300x300", type: :grayscale).processed, class: 'py-4' %>
  <div class="pb-4">
    <h3>Reglas</h3>
    <%= @gameboard.rules %>
    <%= link_to 'Descargar Reglas', rails_blob_path(@gameboard.board_rule, disposition: 'attachment'), class: 'd-block pt-4' %>
  </div>
  <div class="pb-4">
    <h3>Tablero</h3>
    <% @gameboard.board_parts.each do |parts| %>
      <div class="d-inline-flex flex-column">
        <%= image_tag parts.variant(resize: "100x100", type: :grayscale).processed, class: 'pb-3' %>
        <%= link_to 'Descargar Imagen', rails_blob_path(parts, disposition: 'attachment') %>
      </div>
    <% end %>
  </div>
  <div class="pb-4">
    <h3>Piezas</h3>
      <% @gameboard.pieces.each do |piece| %>
      <div class="d-inline-flex flex-column mr-4">
        <%= image_tag piece.variant(resize: "100x100", type: :grayscale).processed, class: 'pb-3' %>
        <%= link_to 'Descargar Imagen', rails_blob_path(piece, disposition: 'attachment') %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="btn-group py-4" role="group" aria-label="Basic example">
    <%= link_to 'Editar', edit_gameboard_path(@gameboard), class: 'btn btn-secondary' %>
    <%= link_to 'Atrás', gameboards_path, class: 'btn btn-outline-secondary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameBoards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Mis Tableros', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Tableros', gameboards_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>